In [1]:
# !pip install pybind11
# !pip install graph-walker
# !pip install pandas
# !pip install numpy
# !pip install networkx


In [2]:
import networkx as nx
import walker
import pandas as pd
import numpy as np
import matplotlib

In [3]:
import networkx as nx
import walker

# create a random graph
G = nx.random_partition_graph([1000] * 15, .01, .001)

# generate random walks
X = walker.random_walks(G, n_walks=50, walk_len=25)

# generate random walks with restart probability alpha
X = walker.random_walks(G, n_walks=50, walk_len=25, alpha=.1)

# you can generate random walks from specified starting nodes
X = walker.random_walks(G, n_walks=50, walk_len=25, start_nodes=[0, 1, 2])

# generate random walks according to Node2Vec methodology by specifying p and q
X = walker.random_walks(G, n_walks=50, walk_len=25, p=.25, q=.25)

# corrupt random walks by randomly changing nodes in random walks
# `y` matrix has a size (N, walk_len - 1) with:
# y[i, j] = 1 if nodes X[i, j] and X[i, j + 1] share an edge, 0 otherwise
y = walker.corrupt(G, X, r=.1)

Random walks - T=0.30s
Random walks - T=0.31s
Random walks - T=0.21s
Random walks - T=0.83s
Corrupt random walks - T=0.27s


Semantic Similarity Graph

In [11]:
# get words and semantic similarity 
words = pd.read_csv("data/alpha_0.0_s2v/vocab.csv")['Word'].tolist()[:20]
sim_mat = pd.read_csv("data/alpha_0.0_s2v/semantic_matrix.csv", header=None, names=list(range(463)))

# get semantic similarity 
word1 = []
word2 = [] 
sim = [] 

for i in range(20):
    j = i  
    while j < 20:
        word1.append(words[i])
        word2.append(words[j])
        sim.append(sim_mat.iloc[i, j])
        j += 1

#create dataframe 
df = pd.DataFrame({'word1' : word1, 'word2' : word2, 'sim' : sim})


FileNotFoundError: [Errno 2] No such file or directory: 'data/alpha_0.0_s2v/vocab.csv'

In [12]:
df

NameError: name 'df' is not defined

In [13]:
# creating graph
Graph = nx.from_pandas_edgelist(df, 'word1', 'word2', ['sim'], create_using=nx.Graph)
# G = nx.from_pandas_edgelist(df, 'word1', 'word2', ['sim', 'weight', 'capacity'], create_using=nx.Graph)
nx.draw(Graph, with_labels=True)

NameError: name 'df' is not defined

In [6]:
R = walker.random_walks(Graph, n_walks=2, walk_len=7, alpha=.1)

Random walks - T=0.00s


In [7]:
print(len(R))
print(R)


40
[[ 0 10  5  7 13  3 16]
 [ 1  0 15 10 17  4  8]
 [ 2  6 12  4 17  0  2]
 [ 3 10  0 11 11  0 15]
 [ 4 19 18 16  8 17  5]
 [ 5  0  6 13 10 10 13]
 [ 6  7  6 19  6 15 14]
 [ 7 17  7  7  8  7  1]
 [ 8  1 15  0  9 12 17]
 [ 9 17  9 13  9  4  1]
 [10 10 10 10 18 13 14]
 [11 17 15 11  9  6 16]
 [12 17  6  2  8  7  7]
 [13 15  5  1 13  8 10]
 [14  6 13  6  7 17  1]
 [15  7  3  3  8 13  0]
 [16 16 15  0 13 15 14]
 [17  7 16 18 14  4 15]
 [18  7 15 10 12 16 18]
 [19 10  5 12  3 14 15]
 [ 0  0  9  8 10  9  0]
 [ 1 10  1 15  2 16  1]
 [ 2  6  1 19  0 19  7]
 [ 3  5  3 17 16 19  7]
 [ 4  1  1  8  1 12  3]
 [ 5 13  1 18  8 13  5]
 [ 6 17 11  6 14 10  3]
 [ 7  2  8 15 16  6 18]
 [ 8  8 11  0  8  1  4]
 [ 9 18  8  9 19 11  8]
 [10  3  5 16 19 10  0]
 [11 11  3 17  1 12  3]
 [12  6  3  8  0 12 12]
 [13  0  1  6  2 13 11]
 [14  6 18  2  4 12 14]
 [15 16  3  8 17  5 12]
 [16 10 19  2 12  5 17]
 [17  6 12  4  6 17 18]
 [18 10 17 14  9  1 14]
 [19  2 17 12  5 13  4]]


In [8]:
print(R[0])

[ 0 10  5  7 13  3 16]


In [9]:
Graph.nodes()

NodeView(('adder', 'african', 'albatross', 'alligator', 'alpaca', 'american', 'anchovy', 'anemone', 'ant', 'antelope', 'ape', 'asian', 'asp', 'ass', 'australian', 'baboon', 'baby', 'badger', 'bantam', 'basilisk'))